name: Bug Report
description: Melde einen Fehler in NutriKompass
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      description: Was ist passiert?
      placeholder: Klare, kurze Fehlerbeschreibung
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Schritte zum Reproduzieren
      placeholder: |
        1. Gehe zu ...
        2. Klicke auf ...
        3. Fehler erscheint ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Umgebung
      placeholder: Browser, OS, Node-Version, etc.
    validations:
      required: false
